### ISSUE TITLE
Please convert XHTML to HTML5

### ISSUE THREAD

**Issue by towolf** [rgxg/rgxg.github.io#3]
The 90s called and want their end tags back ...

**Comment by hvhaugwitz** [comment]
Currently I don't have the time to convert the website to HTML5. But a pull request would be welcome.

**Comment by towolf** [comment]
Seeing how you closed that other PR (robbing the contributor of his entry in the ChangeLog), I'm not sure that contributions really are welcome.

**Comment by hvhaugwitz** [comment]
I don't intend to work on this in the foreseeable future, hence I close this issue. As said, if someone is seriously interested to help here, a pull request is welcome of course.
