### ISSUE TITLE
FreeBSD port/package is done.

### ISSUE THREAD

**Issue by dorjechang** [rgxg/rgxg.github.io#7]
Hi Hannes,

just to inform you that rgxg was successfully commited to FreeBSD ports tree on 09.03.2021

Commit is [here](https://cgit.freebsd.org/ports/commit/?id=4a6c4a258ae524df314a5a4cee64bfabf7275d99).
Port source is [here](https://github.com/dorjechang/rgxg-FreeBSD-port).

Cheers,
alexander

**Comment by hvhaugwitz** [comment]
This is great. Which command can be used to install AIDE on FreeBSD?

**Comment by dorjechang** [comment]
To install binaries: `pkg install devel/rgxg`
To build from sources: `(cd /usr/ports/devel/rgxg ; make install clean)`
